version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/edgexfoundry/go-mod-core-contracts/*"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-messaging/*"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-registry/*"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-configuration/*"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/edgexfoundry/go-mod-secrets/*"
        # Included when go-mod-bootstrap is updated
      - dependency-name: "github.com/gomodule/redigo"
        # For github.com/gomodule/redigo, ignore version v2.0.0
        versions: ["v2.0.0"]
